updated the readme
hedyhli/gtrending pull request #39
Opened 2021-10-19 14:22 UTC by harsh204016

fix some small mistakes in readme , please review and accept it.

2021-11-01 02:39 UTC, hedyhli requested changes
Almost there! Just keep in mind that we want the docstrings in the API be identical to that of the code.

2021-11-01 02:39 UTC, hedyhli commented on gtrending/fetch.py
> +    """Fetch programming languages.
If you want the docstring to be this, then please update that part in the readme as well

2021-11-01 02:39 UTC, hedyhli commented on gtrending/fetch.py
> +    """Fetch the trending developers on GitHub.
I think it's a bit extra
```suggestion
    """Fetch trending developers on GitHub.
```

2021-12-09 17:33 UTC, harsh204016 commented
Hi @hedyhli , I have updated the readme as requested please review and merge it.

2021-12-12 04:32 UTC, hedyhli reviewed
Thanks!

2021-12-12 04:34 UTC, hedyhli approved these changes

2021-12-12 04:38 UTC, merged